### ISSUE TITLE
SyntaxError: Unexpected identifier

### ISSUE THREAD

**Issue by wilsonbiggs** [Zequez/reddit-placebot#22]
Heya. I'm getting an error:

```
/home/wbiggs/reddit-placebot/run.js:24
for (let user in users) { if (!queues[user]) scheduleUser(user) }
         ^^^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
npm ERR! weird error 8
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian

npm ERR! not ok code 0
```

Any clue what might be causing this?

**Comment by wilsonbiggs** [comment]
I had to update node, by bad!
