### ISSUE TITLE
/tmp/cookies.json doesn't exist

### ISSUE THREAD

**Issue by cjwelborn** [Zequez/reddit-placebot#26]
Looks like the refactor messed things up a bit:
```
> reddit-placebot@1.0.0 start /home/cj/clones/reddit-placebot
> node src/run.js "src/run"

fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/home/cj/clones/reddit-placebot/src/../tmp/cookies.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at Object.<anonymous> (/home/cj/clones/reddit-placebot/src/cookies.js:4:30)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/cj/clones/reddit-placebot/src/authentication.js:3:17)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
```

Fixed with:
```bash
mkdir tmp
echo "{}" > tmp/cookies.json
```

**Comment by Zequez** [comment]
Yeah, I forgot to make sure `/tmp/`  wasn't ignored, I just fixed it on the last commit.
