### ISSUE TITLE
Cannot read property 'cookie' of undefined

### ISSUE THREAD

**Issue by lukeramsden** [Zequez/reddit-placebot#32]
Got that error when I tried to run it. I wanted to try using a large list with a mix of valid and invalid accounts, and it seems to have broke it :P

**Comment by lukeramsden** [comment]
Seems to be unhandled Promise:

```
Unhandled rejection TypeError: Cannot read property 'cookie' of undefined
    at userPaint (C:\Users\luker\Desktop\reddit-placebot\src\run.js:75:21)
    at availableUsers.forEach (C:\Users\luker\Desktop\reddit-placebot\src\run.js:48:27)
    at Array.forEach (native)
    at boardDiffer.then (C:\Users\luker\Desktop\reddit-placebot\src\run.js:45:24)
    at tryCatcher (C:\Users\luker\Desktop\reddit-placebot\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\luker\Desktop\reddit-placebot\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\luker\Desktop\reddit-placebot\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\luker\Desktop\reddit-placebot\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\luker\Desktop\reddit-placebot\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (C:\Users\luker\Desktop\reddit-placebot\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (C:\Users\luker\Desktop\reddit-placebot\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (C:\Users\luker\Desktop\reddit-placebot\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

**Comment by Zequez** [comment]
Invalid accounts will throw an error. Maybe we can make it so it just ignores them.

**Comment by Zequez** [comment]
There you go, happy dumping 😂

**Comment by lukeramsden** [comment]
@Zequez thanks :P
