### ISSUE TITLE
Unhandled rejection Error: Request failed with status code 503

### ISSUE THREAD

**Issue by xpopy** [Zequez/reddit-placebot#42]
```
Unhandled rejection Error: Request failed with status code 503
    at createError (C:\Users\oskar\Desktop\reddit-placebot-e8abb8aa8d82600f9fa7273c250de49028513e45\node_modules\axios\lib\core\createError.js:15:15)
    at settle (C:\Users\oskar\Desktop\reddit-placebot-e8abb8aa8d82600f9fa7273c250de49028513e45\node_modules\axios\lib\core\settle.js:18:12)
    at IncomingMessage.handleStreamEnd (C:\Users\oskar\Desktop\reddit-placebot-e8abb8aa8d82600f9fa7273c250de49028513e45\node_modules\axios\lib\adapters\http.js:186:11)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:188:7)
    at endReadableNT (_stream_readable.js:975:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

It works if I restart it, but happened twice now. Any idea why?

**Comment by Lenni** [comment]
Probably you tried to participate with an Account which has been created after the 31st of May

**Comment by Lenni** [comment]
The Servers are under really heavy load right now. More than 100.000 people are connected to it.

**Comment by xpopy** [comment]
Makes sense, would be nice if Zequez could patch it though, so maybe it would try again after some delay

**Comment by Lenni** [comment]
Oh well, nevermind. /r/place has ended right now

**Comment by xpopy** [comment]
Just noticed, thought it would go on for longer
