### ISSUE TITLE
help.

### ISSUE THREAD

**Issue by iBlz** [Zequez/reddit-placebot#49]
Unhandled rejection Error: Request failed with status code 403
    at createError (/root/reddit-placebot/node_modules/axios/lib/core/createError.js:15:15)
    at settle (/root/reddit-placebot/node_modules/axios/lib/core/settle.js:18:12)
    at IncomingMessage.handleStreamEnd (/root/reddit-placebot/node_modules/axios/lib/adapters/http.js:186:11)
    at IncomingMessage.emit (events.js:326:22)
    at endReadableNT (_stream_readable.js:1241:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)

**Comment by mrfortest** [comment]
Same here
